import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome',
      'services': 'Services',
      'appointments': 'Appointments',
      'home': 'Home',
      'greeting': 'Welcome back!',
      'legal_services': 'Legal services',
      'popular_lawyers': 'Popular lawyers',
      'coming_soon': 'This section will be available soon',
      'chat': 'Chat',
      'community': 'Community',
      'profile': 'Profile',
      'money_transfer': 'Money Transfer',
      'consular': 'Consular',
      'translation': 'Translation',
      'market': 'Market',
      'career_center': 'Career Center',
      'ai_assistant': 'AI Assistant',
      'emergency': 'Emergency',
      'scheduled_transfer': 'Scheduled Transfer',
      'currency_rates': 'Currency Rates',
      'transaction_history': 'Transaction History',
      'settings': 'Settings',
      'logout': 'Logout',
      'search': 'Search',
      'verify': 'Verify',
      'news': 'News',
      'see_all': 'See All',
      'language': 'Language',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'back': 'Back',
      'loading': 'Loading...',
      'no_data': 'No data found',
      'error': 'An error occurred',
      'verified': 'Verified',
      'trust_rating': 'Trust Rating',
      'points': 'Points',
      'my_applications': 'My Applications',
      'saved': 'Saved',
      'payment_history': 'Payment History',
      'my_queues': 'My Queues',
      'sponsor_rating': 'Sponsors Rating',
      'support': 'Support',
      'exit_app': 'Exit Application',
      'skip': 'Skip',
      'onboarding_title': 'Connect with Compatriots',
      'onboarding_desc':
          'Stay in touch with your loved ones through chat, community and networking.',
      'next': 'Next',
      'welcome_title': 'Welcome back!',
      'login_subtitle': 'Enter your phone number to continue.',
      'phone_hint': '111 11 11',
      'terms_and_privacy':
          'I accept the Terms of Use and Privacy Policy.',
      'continue': 'Continue',
      'otp_title': 'Verification Code',
      'otp_subtitle': 'Enter the 6-digit code sent via SMS.',
      'resend_code': 'Resend code',
      'verify_code': 'Confirm code',
      'personal': 'Personal',
      'groups': 'Groups',
      'channels': 'Channels',
      'me': 'Me',
      'online': 'Online',
      'today': 'Today',
      'type_message': 'Type a message',
      'events': 'Events',
      'nearby_users': 'Compatriots around',
      'open_in_map': 'Open in map',
      'select_language': 'Choose language',
      'select_language_subtitle':
          'Choose the most comfortable language for using the app.',
      'appearance': 'Appearance',
      'theme_mode': 'Theme mode',
      'system_default': 'System default',
      'light_mode': 'Light mode',
      'dark_mode': 'Dark mode',
      'change_language': 'Change language',
      'current_language': 'Current language',
      'preferences': 'Preferences',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'Edit profile',
      'profile_updated': 'Profile updated successfully',
      'save': 'Save',
      'first_name': 'First name',
      'last_name': 'Last name',
      'middle_name': 'Middle name',
      'username_label': 'Username',
      'location_unknown': 'Location unavailable',
      'reward_shop': 'Rewards shop',
      'logout_confirm_title': 'Log out',
      'logout_confirm_message': 'Are you sure you want to log out?',
      'exit': 'Exit',
      'current_location': 'Current location',
      'tap_to_edit': 'Tap to edit',
      'home_error_title': 'Error',
      'ok': 'OK',
      'news_search_hint': 'Search news...',
      'filter_by_date': 'Filter by date',
      'all': 'All',
      'category_news': 'News',
      'events_title': 'Events',
      'event_search_hint': 'Search event or location...',
      'chat_create_group': 'Create new group',
      'chat_group_name': 'Group name',
      'chat_group_about_optional': 'About group (optional)',
      'city_optional': 'City (optional)',
      'invite_link': 'Invite link',
      'example_group_name': 'for example: group_name',
      'group_type': 'Group type',
      'public': 'Public',
      'private': 'Private',
      'create': 'Create',
      'chat_create_channel': 'Create new channel',
      'chat_channel_name': 'Channel name',
      'chat_channel_about_optional': 'About channel (optional)',
      'example_channel_name': 'for example: channel_name',
      'channel_type': 'Channel type',
      'no_groups_yet': 'No groups yet',
      'no_channels_yet': 'No channels yet',
      'no_chats_yet': 'No chats yet',
      'members': 'members',
      'subscribers': 'subscribers',
      'nearby_prefix': 'Nearby',
      'edit': 'Edit',
      'pin': 'Pin',
      'unpin': 'Unpin',
      'delete': 'Delete',
      'edit_message': 'Edit message',
      'delete_message_title': 'Delete?',
      'delete_message_confirm': 'Do you really want to delete this message?',
      'no': 'No',
      'yes': 'Yes',
      'edit_group': 'Edit group',
      'delete_group': 'Delete group',
      'leave_group': 'Leave group',
      'edit_channel': 'Edit channel',
      'delete_channel': 'Delete channel',
      'leave_channel': 'Leave channel',
      'chat_group_about': 'About group',
      'city': 'City',
      'delete_group_title': 'Delete group?',
      'delete_group_confirm': 'Do you really want to delete this group permanently?',
      'yes_delete': 'Yes, delete',
      'delete_channel_title': 'Delete channel?',
      'delete_channel_confirm': 'Do you really want to delete this channel permanently?',
      'group': 'Group',
      'channel': 'Channel',
      'pinned_message': 'Pinned message',
      'pinned': 'Pinned',
      'edited': 'edited',
      'copy': 'Copy',
      'copied': 'Copied',
      'done': 'Done',
      'community_title': 'Events and communities',
      'success_stories_title': 'Success stories',
      'charity_fund_title': 'Charity fund',
      'live_streams_title': 'Live streams',
      'send': 'Send',
      'collected': 'collected',
      'of_goal': 'of',
      'system_error': 'A system error occurred',
      'closed': 'Closed',
      'attend': 'Attend',
      'cancel_attendance': 'Cancel attendance',
      'attendance_confirmed': 'Attendance confirmed',
      'attendance_cancelled': 'Attendance cancelled',
      'action_failed': 'Action failed',
      'support_sent': 'Support sent successfully',
      'support_failed': 'Support was not sent',
      'career_center_title': 'Career Center',
      'no_saved_vacancies': 'No saved vacancies found',
      'no_vacancies': 'No vacancies found',
      'retry': 'Retry',
      'per_month': '/month',
      'vacancy_not_found': 'Vacancy not found',
      'vacancy_detail': 'Vacancy details',
      'job_about': 'About the job',
      'requirements_title': 'Requirements',
      'organization_about': 'About organization',
      'address': 'Address',
      'specialist_contact': 'Contact specialist',
      'employees_count_more_than': 'employees',
      'specialist': 'Specialist',
      'apply': 'Apply',
      'application_closed': 'Applications closed',
      'enter_first_last_name': 'Enter first name and last name',
      'application_sent': 'Application sent successfully',
      'application_failed': 'Could not send application',
      'check_info_before_apply': 'Check the information before applying',
      'phone_number_label': 'Phone number',
      'application_not_found': 'Application not found',
      'status_history': 'Status history',
      'application_detail': 'Application details',
      'application_number': 'Application number',
      'submitted_date': 'Submission date',
      'application_status': 'Application status',
      'no_history_available': 'No history available',
      'consular_appointment_title': 'Book an appointment',
      'select_country_city': 'Select country and city',
      'select_nearby_consulate': 'Select the consular institution closest to you.',
      'select_country': 'Select country',
      'select_institution': 'Select institution',
      'select_service_type': 'Select service type',
      'select_required_service': 'Select the service you need and book an appointment.',
      'biometric_passport': 'Biometric passport',
      'biometric_passport_desc': 'Apply for a new international passport...',
      'visa_issues': 'Visa issues',
      'visa_issues_desc': 'Obtain or extend a visa for foreign citizens...',
      'notary_services': 'Notary services',
      'notary_services_desc': 'Certify powers of attorney and applications',
      'select_date_time': 'Select date and time',
      'select_convenient_date_time': 'Choose a convenient date and time for you.',
      'date_placeholder': 'dd.mm.yyyy',
      'available_slots': 'Available times',
      'appointment_success': 'Your appointment\nwas booked successfully.',
      'service_type': 'Service type',
      'location': 'Location',
      'date': 'Date',
      'time': 'Time',
      'id_number': 'ID number',
      'tap_qr_to_view': 'Tap to view the full QR code',
      'note': 'Note',
      'queue_manage_note': 'To review, change, or cancel your appointment, go to My Queues in the Profile page.',
      'back_to_home': 'Back to home',
      'notifications': 'Notifications',
      'no_notifications_yet': 'No notifications yet',
      'contribute_title': 'Contribute',
      'grow_with_us': 'Grow with us',
      'contribute_desc': 'Be part of our project connecting 2 million users. Your trust and support inspire us to pursue even bigger goals.',
      'amount': 'Amount',
      'enter_amount': 'Enter amount',
      'anonymous_contribution': 'Contribute anonymously',
      'please_enter_amount': 'Please enter an amount',
      'invalid_amount': 'Invalid amount',
      'thank_you_contribution': 'Thank you for your contribution!',
      'contribution_error': 'An error occurred. Please try again.',
      'payment_receipt': 'Payment receipt',
      'transaction_id': 'Transaction ID',
      'recipient': 'Recipient',
      'amount_label': 'Amount',
      'commission': 'Commission',
      'total_amount': 'Total amount',
      'completed_successfully': 'Completed successfully',
      'translation_title': 'Translation',
      'photo_taken_processing': 'Photo captured: {name}. Detecting text...',
      'file_uploaded': 'File uploaded: {name}',
      'translate_from': 'From which language',
      'translate_to': 'To which language',
      'enter_text': 'Enter text',
      'translation_placeholder': 'Translation',
      'camera': 'Camera',
      'voice': 'Voice',
      'document': 'Document',
      'emergency_title': 'Emergency assistance',
      'hold_red_button': 'Hold the red button for 3 seconds',
      'help': 'Help',
      'help_types': 'Help types',
      'trusted_contacts': 'Trusted contacts',
      'nearby_help': 'Nearby\nhelp',
      'ai_helper': 'AI assistant',
      'test_sos_notification': 'Test SOS\nnotification',
      'test_sos_sent': 'Test SOS notification sent',
      'transaction_history_title': 'Transaction history',
      'no_transactions_found': 'No transactions found',
      'successful_transfer': 'Successful transfer',
      'recipient_name': 'Recipient name',
      'sender_name': 'Sender name',
      'sender': 'Sender',
      'view_receipt': 'View receipt',
      'download_receipt': 'Download receipt',
      'currency_rates_title': 'Currency rates',
      'no_information_found': 'No information found',
      'sos_alert_title': 'SOS alert',
      'sos_type_label': 'SOS type',
      'sos_reporter_role': 'User who sent SOS',
      'sos_reporter_title': 'User who sent SOS',
      'medical_help': 'Medical help',
      'fire_help': 'Fire',
      'police_help': 'Police',
      'general_help': 'General help',
      'sos_default_description': 'A user nearby sent an emergency help signal.',
      'gps_coordinates_detected': 'GPS coordinates detected',
      'compatriots_notified': 'Compatriots notified',
      'consulate_notified': 'Consulate notified',
      'trusted_contacts_notified': 'Trusted contacts notified',
      'locating_nearby_compatriots': 'Detecting nearby compatriots...',
      'nearby_compatriots_found': '{count} nearby compatriots found',
      'notified_and_responded': 'Notified and responded',
      'view': 'View',
      'view_on_map': 'View on map',
      'i_am_safe': 'I am safe',
      'location_shared_with_contacts': 'Your location will be shared with trusted contacts',
      'medical_assistance': 'Medical help',
      'police_assistance': 'Police assistance',
      'lost_documents': 'Lost documents',
      'physical_safety': 'Physical safety',
      'other': 'Other',
      'my_applications_title': 'My applications',
      'application_search_hint': 'By application ID or service name...',
      'no_applications_found': 'No applications found',
      'clear_filters': 'Clear filters',
      'filter_by_status': 'Filter by status',
      'application_number_label': 'Application number: ',
      'categories': 'Categories',
      'products': 'Products',
      'no_products_found': 'No products found',
      'categories_not_found': 'No categories found',
      'consular_detail_title': 'Consular details',
      'consular_list_title': 'Consulates list',
      'phone_number': 'Phone number',
      'email': 'Email',
      'work_hours': 'Working hours',
      'consular_services': 'Consular services',
      'renew_passport': 'Passport renewal',
      'visa_services': 'Visa services',
      'frequently_asked_questions': 'Frequently asked questions',
      'contact': 'Contact',
      'nearby_consulates': 'Nearby consulates',
      'consulates_list': 'Consulates list',
      'scheduled_transfer_title': 'Scheduled transfer',
      'search_phone_or_card': 'By phone number or card...',
      'scheduled_transfer_list': 'Scheduled transfers list',
      'unknown': 'Unknown',
      'recurrence': 'Recurrence',
      'every_month': 'Every month',
      'every_month_day_5': 'Every month on the 5th',
      'manual_schedule': 'Set manually',
      'manual_schedule_desc': 'Choose the month and day yourself',
      'enable_transfer': 'Enable transfer',
      'auto_send_money': 'Send money automatically',
      'select_payment_method': 'Select payment method',
      'no_payment_methods': 'No payment methods found',
      'add_payment_method_profile': 'Please add a payment method in the profile section',
      'pay_via': 'Pay via {type}',
      'exchange_rate': 'Exchange rate',
      'payment': 'Payment',
      'confirm_transfer': 'Confirm transfer',
      'face_position_instruction': 'Place your face correctly inside the circle',
      'payment_failed': 'An error occurred while processing the payment.',
      'face_verification_failed': 'Face verification failed. Please try again.',
      'myid_verification': 'Verification via MyID',
      'verify_face_to_complete_payment': 'Verify your face to complete the payment',
      'transfer_successful': 'Transfer completed successfully!',
      'downloading_receipt': 'Downloading receipt...',
      'receipt_downloaded': 'Receipt downloaded successfully',
      'project_sponsors': 'Project sponsors',
      'recent': 'Recent',
      'error_with_message': 'Error: {message}',
      'add_recipient': 'Add recipient',
      'mock_translation': 'Mock translation: {text}',
      'emergency_assistance':'Emergency assistance',
      'select_emergency_situation':'Select an emergency situation',
      'medical_care':'Medical care',
      'Other':'Other',
      'consular_messages':'Consular messages',
    },
    'uz': {
      'welcome': 'Xush kelibsiz!',
      'services': 'Xizmatlar',
      'appointments': 'Qabullar',
      'home': 'Asosiy',
      'greeting': 'Assalomu alaykum!',
      'legal_services': 'Huquqiy xizmatlar',
      'popular_lawyers': 'Mashhur advokatlar',
      'coming_soon': 'Bu bo‘lim tez orada ishga tushadi',
      'chat': 'Chat',
      'community': 'Jamoa',
      'profile': 'Profil',
      'money_transfer': 'Pul o\'tkazish',
      'consular': 'Konsullik',
      'translation': 'Tarjima',
      'market': 'Market',
      'career_center': 'Karyera markazi',
      'ai_assistant': 'AI yordamchi',
      'emergency': 'Favqulodda yordam',
      'scheduled_transfer': 'Rejalashtirilgan o\'tkazma',
      'currency_rates': 'Valyutalar kursi',
      'transaction_history': 'Tranzaksiyalar tarixi',
      'settings': 'Sozlamalar',
      'logout': 'Tizimdan chiqish',
      'search': 'Izlash',
      'verify': 'Verifikatsiya qilish',
      'news': 'Yangiliklar',
      'see_all': 'Barchasi',
      'language': 'Til',
      'confirm': 'Tasdiqlash',
      'cancel': 'Bekor qilish',
      'back': 'Orqaga',
      'loading': 'Yuklanmoqda...',
      'no_data': 'Ma\'lumot topilmadi',
      'error': 'Xatolik',
      'verified': 'Tasdiqlangan',
      'trust_rating': 'Ishonch reytingi',
      'points': 'Ball',
      'my_applications': 'Mening arizalarim',
      'saved': 'Saqlanganlar',
      'payment_history': 'To\'lovlar tarixi',
      'my_queues': 'Mening navbatlarim',
      'sponsor_rating': 'Homiylar reytingi',
      'support': 'Qo\'llab-quvvatlash',
      'skip': 'O\'tkazib yuborish',
      'onboarding_title': 'Vatandoshlar bilan bog\'laning',
      'onboarding_desc':
      'Chat, community va networking orqali yaqinlaringiz bilan aloqada bo\'ling.',
      'next': 'Keyingisi',
      'login_subtitle':
      'Davom etish uchun telefon raqamingizni kiriting.',
      'phone_hint': '111 11 11',
      'terms_and_privacy':
      'Foydalanish shartlari va Maxfiylik siyosatini qabul qilaman.',
      'continue': 'Davom etish',
      'otp_title': 'Tasdiqlash kodi',
      'otp_subtitle':
      'SMS orqali yuborilgan 6 xonali kodni kiriting.',
      'resend_code': 'Qayta yuborish',
      'verify_code': 'Kodni tasdiqlash',
      'personal': 'Shaxsiy',
      'groups': 'Guruhlar',
      'channels': 'Kanallar',
      'me': 'Men',
      'online': 'Tarmoqda',
      'today': 'Bugun',
      'type_message': 'Yozing',
      'events': 'Tadbirlar',
      'nearby_users': 'Atrofdagi vatandoshlar',
      'open_in_map': 'Xaritadan ochish',
      'select_language': 'Tilni tanlang',
      'select_language_subtitle':
      'Ilovadan qulay foydalanish uchun o\'zingizga mos tilni tanlang.',
      'appearance': 'Ko\'rinish',
      'theme_mode': 'Mavzu rejimi',
      'system_default': 'Tizim bo\'yicha',
      'light_mode': 'Yorug\' rejim',
      'dark_mode': 'Qorong\'i rejim',
      'change_language': 'Tilni o\'zgartirish',
      'current_language': 'Joriy til',
      'preferences': 'Sozlamalar',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'Profilni tahrirlash',
      'profile_updated': 'Profil muvaffaqiyatli yangilandi',
      'save': 'Saqlash',
      'first_name': 'Ism',
      'last_name': 'Familiya',
      'middle_name': 'Sharif',
      'username_label': 'Username',
      'location_unknown': 'Joylashuv aniqlanmagan',
      'reward_shop': 'Mukofotlar do\'koni',
      'logout_confirm_message': 'Rostdan ham tizimdan chiqmoqchimisiz?',
      'current_location': 'Joriy joylashuv',
      'tap_to_edit': 'Tahrirlash uchun bosing',
      'ok': 'OK',
      'news_search_hint': 'Yangilik nomi...',
      'filter_by_date': 'Sana bo\'yicha filter',
      'all': 'Barchasi',
      'category_news': 'Yangiliklar',
      'event_search_hint': 'Event nomi yoki manzil...',
      'chat_create_group': 'Yangi guruh ochish',
      'chat_group_name': 'Guruh nomi',
      'chat_group_about_optional': 'Guruh haqida (ixtiyoriy)',
      'city_optional': 'Shahar (ixtiyoriy)',
      'invite_link': 'Havola',
      'example_group_name': 'masalan: guruh_nomi',
      'group_type': 'Guruh turi',
      'public': 'Ochiq',
      'private': 'Yopiq',
      'create': 'Yaratish',
      'chat_create_channel': 'Yangi kanal ochish',
      'chat_channel_name': 'Kanal nomi',
      'chat_channel_about_optional': 'Kanal haqida (ixtiyoriy)',
      'example_channel_name': 'masalan: kanal_nomi',
      'channel_type': 'Kanal turi',
      'no_groups_yet': 'Hozircha guruhlar mavjud emas',
      'no_channels_yet': 'Hozircha kanallar mavjud emas',
      'no_chats_yet': 'Hozircha suhbatlar mavjud emas',
      'members': 'a\'zo',
      'subscribers': 'obunachi',
      'nearby_prefix': 'Yaqin atrofda',
      'edit': 'Tahrirlash',
      'pin': 'Pin qilish',
      'unpin': 'Pinni olib tashlash',
      'delete': 'O\'chirish',
      'edit_message': 'Xabarni tahrirlash',
      'delete_message_title': 'O\'chirish?',
      'delete_message_confirm': 'Haqiqatdan ham ushbu xabarni o\'chirmoqchimisiz?',
      'no': 'Yo\'q',
      'yes': 'Ha',
      'edit_group': 'Guruhni tahrirlash',
      'delete_group': 'Guruhni o\'chirish',
      'leave_group': 'Guruhdan chiqish',
      'edit_channel': 'Kanalni tahrirlash',
      'delete_channel': 'Kanalni o\'chirish',
      'leave_channel': 'Kanaldan chiqish',
      'chat_group_about': 'Guruh haqida',
      'city': 'Shahar',
      'delete_group_title': 'Guruhni o\'chirish?',
      'delete_group_confirm': 'Haqiqatdan ham ushbu guruhni butunlay o\'chirib yubormoqchimisiz?',
      'yes_delete': 'Ha, o\'chirilsin',
      'delete_channel_title': 'Kanalni o\'chirish?',
      'delete_channel_confirm': 'Haqiqatdan ham ushbu kanalni butunlay o\'chirib yubormoqchimisiz?',
      'group': 'Guruh',
      'channel': 'Kanal',
      'pinned_message': 'Pin qilingan xabar',
      'pinned': 'Pin',
      'edited': 'tahrirlangan',
      'copy': 'Nusxa olish',
      'copied': 'Nusxa olindi!',
      'done': 'Tayyor',
      'community_title': 'Tadbirlar va jamoalar',
      'success_stories_title': 'Muvaffaqiyat hikoyalari',
      'charity_fund_title': 'Yordam fondi',
      'live_streams_title': 'Jonli efirlar',
      'send': 'Yuborish',
      'collected': 'yig\'ildi',
      'of_goal': 'dan',
      'system_error': 'Tizimda xatolik yuz berdi',
      'closed': 'Yopilgan',
      'attend': 'Qatnashish',
      'cancel_attendance': 'Bekor qilish',
      'attendance_confirmed': 'Tadbirga qatnashish tasdiqlandi',
      'attendance_cancelled': 'Tadbirga qatnashish bekor qilindi',
      'action_failed': 'Amal bajarilmadi',
      'support_sent': 'Yordam muvaffaqiyatli yuborildi',
      'support_failed': 'Yordam yuborilmadi',
      'no_saved_vacancies': 'Saqlangan vakansiyalar topilmadi',
      'no_vacancies': 'Vakansiyalar topilmadi',
      'retry': 'Qayta urinish',
      'per_month': '/oy',
      'vacancy_not_found': 'Vakansiya topilmadi',
      'vacancy_detail': 'Vakansiya tafsiloti',
      'job_about': 'Ish haqida',
      'requirements_title': 'Talablar',
      'organization_about': 'Tashkilot haqida',
      'address': 'Manzil',
      'specialist_contact': 'Mutaxassis bilan bog\'lanish',
      'employees_count_more_than': 'dan ortiq xodim',
      'specialist': 'Mutaxassis',
      'apply': 'Ariza yuborish',
      'application_closed': 'Ariza yopilgan',
      'enter_first_last_name': 'Ism va familiyani kiriting',
      'application_sent': 'Ariza muvaffaqiyatli yuborildi',
      'application_failed': 'Ariza yuborib bo‘lmadi',
      'check_info_before_apply': 'Ariza yuborish uchun ma’lumotlarni tekshiring',
      'phone_number_label': 'Telefon raqami',
      'application_not_found': 'Ariza topilmadi',
      'status_history': 'Holat tarixi',
      'application_detail': 'Ariza tafsiloti',
      'application_number': 'Ariza raqami',
      'submitted_date': 'Yuborilgan sana',
      'application_status': 'Ariza holati',
      'no_history_available': 'Tarix mavjud emas',
      'consular_appointment_title': 'Navbat olish',
      'select_country_city': 'Davlat va shaharni tanlang',
      'select_nearby_consulate': 'O‘zingizga yaqin bo‘lgan konsullik muassasasini tanlang.',
      'select_country': 'Davlat tanlang',
      'select_institution': 'Muassasani tanlang',
      'service_type': 'Xizmat turi',
      'select_required_service': 'O‘zingizga kerakli bo‘lgan xizmatni tanlang va navbat oling.',
      'biometric_passport': 'Biometrik pasport',
      'biometric_passport_desc': 'Yangi xorijga chiqish pasportini rasmiylashtirish...',
      'visa_issues': 'Viza masalalari',
      'visa_issues_desc': 'Chet el fuqarolari uchun viza olish yoki uzaytirish...',
      'notary_services': 'Notariat xizmatlari',
      'notary_services_desc': 'Ishonchnoma, arizalarni tasdiqlash',
      'select_date_time': 'Sana va vaqtni tanlang',
      'select_convenient_date_time': 'O‘zingizga qulay sana va vaqtni tanlashingiz mumkin.',
      'date_placeholder': 'kk.oy.yyyy',
      'available_slots': 'Bo‘sh vaqtlar',
      'appointment_success': 'Sizning navbatingiz\nmuvaffaqiyatli band qilindi.',
      'location': 'Manzil',
      'date': 'Sana',
      'time': 'Vaqt',
      'id_number': 'ID raqami',
      'tap_qr_to_view': 'To‘liq QR kodini ko‘rish uchun ustiga bosing',
      'note': 'Eslatma',
      'queue_manage_note': 'Navbatingizni qayta ko‘rish, o‘zgartirish yoki bekor qilish uchun Profil sahifasidagi Mening navbatlarim bo‘limiga o‘ting.',
      'back_to_home': 'Bosh sahifaga qaytish',
      'notifications': 'Bildirishnomalar',
      'no_notifications_yet': 'Bildirishnomalar hozircha yo‘q',
      'contribute_title': 'Hissa qo‘shish',
      'grow_with_us': 'Biz bilan birga rivojlaning',
      'contribute_desc': '2 million foydalanuvchini birlashtirgan loyihamizning bir qismi bo‘ling. Sizning ishonchingiz va qo‘llab-quvvatlashingiz bizga yanada katta maqsadlar sari intilish uchun ilhom beradi.',
      'amount': 'Summa',
      'enter_amount': 'Summani kiriting',
      'anonymous_contribution': 'Anonim hissa qo‘shish',
      'please_enter_amount': 'Iltimos, summani kiriting',
      'invalid_amount': 'Noto‘g‘ri summa',
      'thank_you_contribution': 'Hissangiz uchun rahmat!',
      'contribution_error': 'Xatolik yuz berdi. Iltimos, qaytadan urinib ko‘ring.',
      'payment_receipt': 'To‘lov kvitansiyasi',
      'transaction_id': 'Tranzaksiya ID',
      'recipient': 'Qabul qiluvchi',
      'amount_label': 'Summa',
      'commission': 'Komissiya',
      'total_amount': 'Umumiy summa',
      'completed_successfully': 'Muvaffaqiyatli yakunlandi',
      'photo_taken_processing': 'Rasm olindi: {name}. Matn aniqlanmoqda...',
      'file_uploaded': 'Hujjat yuklandi: {name}',
      'translate_from': 'Qaysi tildan',
      'translate_to': 'Qaysi tilga',
      'enter_text': 'Matn kiriting',
      'translation_placeholder': 'Tarjima',
      'camera': 'Kamera',
      'voice': 'Ovoz',
      'document': 'Hujjat',
      'hold_red_button': 'Qizil tugmani 3 soniya bosib turing',
      'help': 'Yordam',
      'help_types': 'Yordam turlari',
      'trusted_contacts': 'Ishonchli kontaktlar',
      'nearby_help': 'Yaqin atrofdagi\nyordam',
      'ai_helper': 'AI yordamchi',
      'test_sos_notification': 'Test SOS\nnotification',
      'test_sos_sent': 'Test SOS notification sent',
      'no_transactions_found': 'Tranzaksiyalar topilmadi',
      'successful_transfer': 'Muvaffaqiyatli o‘tkazma',
      'recipient_name': 'Qabul qiluvchi nomi',
      'sender_name': 'Jo‘natuvchi nomi',
      'sender': 'Jo‘natuvchi',
      'view_receipt': 'Chekni ko‘rish',
      'download_receipt': 'Chekni yuklash',
      'no_information_found': 'Maʼlumot topilmadi',
      'sos_alert_title': 'SOS ogohlantirish',
      'sos_type_label': 'SOS turi',
      'sos_reporter_role': 'SOS yuborgan foydalanuvchi',
      'medical_help': 'Tibbiy yordam',
      'fire_help': 'Yong‘in',
      'police_help': 'Politsiya',
      'general_help': 'Umumiy yordam',
      'sos_default_description': 'Yaqin atrofda foydalanuvchi favqulodda yordam signalini yuborgan.',
      'gps_coordinates_detected': 'GPS koordinata aniqlandi',
      'compatriots_notified': 'Vatandoshlarga xabar yuborildi',
      'consulate_notified': 'Konsullikka xabar yuborildi',
      'trusted_contacts_notified': 'Ishonchli kontaktlarga xabar yuborildi',
      'locating_nearby_compatriots': 'Atrofdagi vatandoshlar aniqlanmoqda...',
      'nearby_compatriots_found': 'Atrofda {count} vatandosh aniqlandi',
      'notified_and_responded': 'Xabardor qilingan va javob berilgan',
      'view': 'Ko‘rish',
      'view_on_map': 'Xaritadan ko‘rish',
      'i_am_safe': 'Men xavfsizman',
      'location_shared_with_contacts': 'Joylashuvingiz ishonchli kontaktlar bilan ulashiladi',
      'medical_assistance': 'Tibbiy yordam',
      'police_assistance': 'Politsiya yordami',
      'lost_documents': 'Yo‘qolgan hujjatlar',
      'physical_safety': 'Jismoniy xavfsizlik',
      'other': 'Boshqa',
      'application_search_hint': 'Ariza ID yoki xizmat nomi bo‘yi...',
      'no_applications_found': 'Arizalar topilmadi',
      'clear_filters': 'Filtrlarni tozalash',
      'filter_by_status': 'Holat bo‘yicha filter',
      'application_number_label': 'Ariza raqami: ',
      'categories': 'Kategoriyalar',
      'products': 'Mahsulotlar',
      'no_products_found': 'Mahsulotlar topilmadi',
      'categories_not_found': 'Kategoriyalar topilmadi',
      'consular_detail_title': 'Konsullik tafsiloti',
      'consular_list_title': 'Konsulliklar ro‘yxati',
      'phone_number': 'Telefon raqam',
      'email': 'Elektron pochta',
      'work_hours': 'Ish vaqti',
      'consular_services': 'Konsullik xizmatlari',
      'renew_passport': 'Pasport yangilash',
      'visa_services': 'Viza xizmatlari',
      'frequently_asked_questions': 'Ko‘p beriladigan savollar',
      'contact': 'Bog‘lanish',
      'nearby_consulates': 'Atrofdagi konsulliklar',
      'search_phone_or_card': 'Telefon raqam yoki karta orqali o‘t...',
      'scheduled_transfer_list': 'Rejalashtirilgan o‘tkazmalar ro‘yxati',
      'unknown': 'Noma’lum',
      'recurrence': 'Takrorlanish',
      'every_month': 'Har oy',
      'every_month_day_5': 'Har oyning 5-sanasi',
      'manual_schedule': 'Qo‘lda belgilash',
      'manual_schedule_desc': 'O‘zingiz hohlagan oy va kuni belgilang',
      'enable_transfer': 'O‘tkazmani yoqish',
      'auto_send_money': 'Pulni avtomatik yuborish',
      'select_payment_method': 'To‘lov usulini tanlang',
      'no_payment_methods': 'To‘lov usullari topilmadi',
      'add_payment_method_profile': 'Iltimos, profil bo‘limida to‘lov usulini qo‘shing',
      'pay_via': '{type} orqali to‘lov',
      'exchange_rate': 'Valuta kursi',
      'payment': 'To‘lov',
      'confirm_transfer': 'O‘tkazmani tasdiqlash',
      'face_position_instruction': 'Yuzingizni doira ichiga to‘g‘rilab joylashtiring',
      'payment_failed': 'To‘lovni amalga oshirishda xatolik yuz berdi.',
      'face_verification_failed': 'Yuzni tasdiqlashda xatolik yuz berdi. Qayta urinib ko‘ring.',
      'myid_verification': 'MyID orqali tasdiqlash',
      'verify_face_to_complete_payment': 'To‘lovni yakunlash uchun yuzingizni tasdiqlang',
      'transfer_successful': 'O‘tkazma muvaffaqiyatli amalga oshirildi!',
      'downloading_receipt': 'Chek yuklab olinmoqda...',
      'receipt_downloaded': 'Chek muvaffaqiyatli yuklab olindi',
      'project_sponsors': 'Loyiha homiylari',
      'recent': 'Yaqinda',
      'error_with_message': 'Xatolik: {message}',
      'add_recipient': 'Qabul qiluvchi qo‘shish',
      'mock_translation': 'Bu mock tarjima: {text}',
      'emergency_assistance': 'Favqulodda yordam',
      'select_emergency_situation': 'Favqulodda holatni tanlang',
      'medical_care': 'Tibbiy yordam',
      'Other': 'Boshqalar',
      'compatriots_around':'Atrofdagi vatandoshlar',
      'no_users_found_nearby':'Yaqin atrofda foydalanuvchilar topilmadi',
      'consular_messages': 'Konsullik xabarlari'
    },
    'ru': {
      'welcome': 'Добро пожаловать',
      'services': 'Услуги',
      'appointments': 'Приёмы',
      'home': 'Главная',
      'greeting': 'Здравствуйте!',
      'legal_services': 'Юридические услуги',
      'popular_lawyers': 'Популярные адвокаты',
      'coming_soon': 'Этот раздел скоро будет доступен',
      'chat': 'Чат',
      'community': 'Сообщество',
      'profile': 'Профиль',
      'money_transfer': 'Денежный перевод',
      'consular': 'Консульство',
      'translation': 'Перевод',
      'market': 'Маркет',
      'career_center': 'Карьерный центр',
      'ai_assistant': 'ИИ помощник',
      'emergency': 'Экстренная помощь',
      'scheduled_transfer': 'Запланированный перевод',
      'currency_rates': 'Курсы валют',
      'transaction_history': 'История транзакций',
      'settings': 'Настройки',
      'logout': 'Выйти',
      'search': 'Поиск',
      'verify': 'Верификация',
      'news': 'Новости',
      'see_all': 'Все',
      'language': 'Язык',
      'confirm': 'Подтвердить',
      'cancel': 'Отмена',
      'back': 'Назад',
      'loading': 'Загрузка...',
      'no_data': 'Данные не найдены',
      'error': 'Произошла ошибка',
      'verified': 'Подтверждено',
      'trust_rating': 'Рейтинг доверия',
      'points': 'Баллы',
      'my_applications': 'Мои заявки',
      'saved': 'Сохранённое',
      'payment_history': 'История платежей',
      'my_queues': 'Мои очереди',
      'sponsor_rating': 'Рейтинг спонсоров',
      'support': 'Поддержка',
      'exit_app': 'Выйти из приложения',
      'skip': 'Пропустить',
      'onboarding_title': 'Оставайтесь на связи с соотечественниками',
      'onboarding_desc':
          'Общайтесь и оставайтесь на связи через чат, сообщество и нетворкинг.',
      'next': 'Далее',
      'welcome_title': 'С возвращением!',
      'login_subtitle': 'Введите номер телефона, чтобы продолжить.',
      'phone_hint': '111 11 11',
      'terms_and_privacy':
          'Я принимаю Условия использования и Политику конфиденциальности.',
      'continue': 'Продолжить',
      'otp_title': 'Код подтверждения',
      'otp_subtitle': 'Введите 6-значный код из SMS.',
      'resend_code': 'Отправить снова',
      'verify_code': 'Подтвердить код',
      'personal': 'Личные',
      'groups': 'Группы',
      'channels': 'Каналы',
      'me': 'Я',
      'online': 'В сети',
      'today': 'Сегодня',
      'type_message': 'Введите сообщение',
      'events': 'События',
      'nearby_users': 'Соотечественники рядом',
      'open_in_map': 'Открыть на карте',
      'select_language': 'Выберите язык',
      'select_language_subtitle':
          'Выберите язык, на котором вам удобнее пользоваться приложением.',
      'appearance': 'Оформление',
      'theme_mode': 'Режим темы',
      'system_default': 'Как в системе',
      'light_mode': 'Светлая тема',
      'dark_mode': 'Тёмная тема',
      'change_language': 'Изменить язык',
      'current_language': 'Текущий язык',
      'preferences': 'Настройки',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'Редактировать профиль',
      'profile_updated': 'Профиль успешно обновлён',
      'save': 'Сохранить',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'middle_name': 'Отчество',
      'username_label': 'Username',
      'location_unknown': 'Местоположение недоступно',
      'reward_shop': 'Магазин наград',
      'logout_confirm_title': 'Выход',
      'logout_confirm_message': 'Вы действительно хотите выйти?',
      'exit': 'Выйти',
      'current_location': 'Текущее местоположение',
      'tap_to_edit': 'Нажмите для редактирования',
      'home_error_title': 'Ошибка',
      'ok': 'OK',
      'news_search_hint': 'Поиск новостей...',
      'filter_by_date': 'Фильтр по дате',
      'all': 'Все',
      'category_news': 'Новости',
      'events_title': 'События',
      'event_search_hint': 'Поиск события или адреса...',
      'chat_create_group': 'Создать новую группу',
      'chat_group_name': 'Название группы',
      'chat_group_about_optional': 'О группе (необязательно)',
      'city_optional': 'Город (необязательно)',
      'invite_link': 'Ссылка-приглашение',
      'example_group_name': 'например: group_name',
      'group_type': 'Тип группы',
      'public': 'Публичная',
      'private': 'Приватная',
      'create': 'Создать',
      'chat_create_channel': 'Создать новый канал',
      'chat_channel_name': 'Название канала',
      'chat_channel_about_optional': 'О канале (необязательно)',
      'example_channel_name': 'например: channel_name',
      'channel_type': 'Тип канала',
      'no_groups_yet': 'Групп пока нет',
      'no_channels_yet': 'Каналов пока нет',
      'no_chats_yet': 'Чатов пока нет',
      'members': 'участников',
      'subscribers': 'подписчиков',
      'nearby_prefix': 'Рядом',
      'edit': 'Редактировать',
      'pin': 'Закрепить',
      'unpin': 'Открепить',
      'delete': 'Удалить',
      'edit_message': 'Редактировать сообщение',
      'delete_message_title': 'Удалить?',
      'delete_message_confirm': 'Вы действительно хотите удалить это сообщение?',
      'no': 'Нет',
      'yes': 'Да',
      'edit_group': 'Редактировать группу',
      'delete_group': 'Удалить группу',
      'leave_group': 'Покинуть группу',
      'edit_channel': 'Редактировать канал',
      'delete_channel': 'Удалить канал',
      'leave_channel': 'Покинуть канал',
      'chat_group_about': 'О группе',
      'city': 'Город',
      'delete_group_title': 'Удалить группу?',
      'delete_group_confirm': 'Вы действительно хотите удалить эту группу навсегда?',
      'yes_delete': 'Да, удалить',
      'delete_channel_title': 'Удалить канал?',
      'delete_channel_confirm': 'Вы действительно хотите удалить этот канал навсегда?',
      'group': 'Группа',
      'channel': 'Канал',
      'pinned_message': 'Закреплённое сообщение',
      'pinned': 'Закреплено',
      'edited': 'изменено',
      'career_center_title': 'Карьерный центр',
      'no_saved_vacancies': 'Сохранённые вакансии не найдены',
      'no_vacancies': 'Вакансии не найдены',
      'retry': 'Повторить',
      'per_month': '/мес',
      'vacancy_not_found': 'Вакансия не найдена',
      'vacancy_detail': 'Детали вакансии',
      'job_about': 'О работе',
      'requirements_title': 'Требования',
      'organization_about': 'О компании',
      'address': 'Адрес',
      'specialist_contact': 'Связаться со специалистом',
      'employees_count_more_than': 'сотрудников',
      'specialist': 'Специалист',
      'apply': 'Откликнуться',
      'application_closed': 'Приём заявок закрыт',
      'enter_first_last_name': 'Введите имя и фамилию',
      'application_sent': 'Заявка успешно отправлена',
      'application_failed': 'Не удалось отправить заявку',
      'check_info_before_apply': 'Проверьте данные перед отправкой заявки',
      'phone_number_label': 'Номер телефона',
      'emergency_assistance': 'Экстренная помощь',
      'select_emergency_situation': 'Выберите экстренную ситуацию',
      'medical_care': 'Медицинская помощь',
      'Other': 'Другое',
      'compatriots_around': 'Соотечественники рядом',
      'no_users_found_nearby': 'Поблизости пользователи не найдены',
      'view_on_map': 'Посмотреть на карте',
      'consular_messages': 'Консульские сообщения'
    },
    'ko': {
      'settings': '설정',
      'language': '언어',
      'continue': '계속',
      'select_language': '언어 선택',
      'select_language_subtitle': '앱에서 사용할 언어를 선택하세요.',
      'appearance': '화면 모드',
      'theme_mode': '테마 모드',
      'system_default': '시스템 기본값',
      'light_mode': '라이트 모드',
      'dark_mode': '다크 모드',
      'change_language': '언어 변경',
      'current_language': '현재 언어',
      'preferences': '환경설정',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': '프로필 수정',
      'profile_updated': '프로필이 업데이트되었습니다',
      'save': '저장',
      'first_name': '이름',
      'last_name': '성',
      'middle_name': '중간 이름',
      'username_label': '사용자 이름',
      'location_unknown': '위치를 확인할 수 없습니다',
      'reward_shop': '보상 상점',
      'logout_confirm_title': '로그아웃',
      'logout_confirm_message': '정말 로그아웃하시겠습니까?',
      'exit': '나가기',
      'current_location': '현재 위치',
      'tap_to_edit': '수정하려면 탭하세요',
      'home_error_title': '오류',
      'ok': '확인',
      'news_search_hint': '뉴스 검색...',
      'filter_by_date': '날짜별 필터',
      'all': '전체',
      'category_news': '뉴스',
      'events_title': '이벤트',
      'event_search_hint': '이벤트 또는 위치 검색...',
      'chat_create_group': '새 그룹 만들기',
      'chat_group_name': '그룹 이름',
      'chat_group_about_optional': '그룹 소개(선택)',
      'city_optional': '도시(선택)',
      'invite_link': '초대 링크',
      'example_group_name': '예: group_name',
      'group_type': '그룹 유형',
      'public': '공개',
      'private': '비공개',
      'create': '만들기',
      'chat_create_channel': '새 채널 만들기',
      'chat_channel_name': '채널 이름',
      'chat_channel_about_optional': '채널 소개(선택)',
      'example_channel_name': '예: channel_name',
      'channel_type': '채널 유형',
      'no_groups_yet': '그룹이 아직 없습니다',
      'no_channels_yet': '채널이 아직 없습니다',
      'no_chats_yet': '채팅이 아직 없습니다',
      'members': '명',
      'subscribers': '구독자',
      'nearby_prefix': '근처',
      'edit': '수정',
      'pin': '고정',
      'unpin': '고정 해제',
      'delete': '삭제',
      'edit_message': '메시지 수정',
      'delete_message_title': '삭제할까요?',
      'delete_message_confirm': '이 메시지를 삭제하시겠습니까?',
      'no': '아니요',
      'yes': '예',
      'edit_group': '그룹 수정',
      'delete_group': '그룹 삭제',
      'leave_group': '그룹 나가기',
      'edit_channel': '채널 수정',
      'delete_channel': '채널 삭제',
      'leave_channel': '채널 나가기',
      'chat_group_about': '그룹 소개',
      'city': '도시',
      'delete_group_title': '그룹을 삭제할까요?',
      'delete_group_confirm': '이 그룹을 완전히 삭제하시겠습니까?',
      'yes_delete': '예, 삭제',
      'delete_channel_title': '채널을 삭제할까요?',
      'delete_channel_confirm': '이 채널을 완전히 삭제하시겠습니까?',
      'group': '그룹',
      'channel': '채널',
      'pinned_message': '고정된 메시지',
      'pinned': '고정됨',
      'edited': '수정됨',
      'career_center_title': '커리어 센터',
      'no_saved_vacancies': '저장된 채용공고가 없습니다',
      'no_vacancies': '채용공고가 없습니다',
      'retry': '다시 시도',
      'per_month': '/월',
      'vacancy_not_found': '채용공고를 찾을 수 없습니다',
      'vacancy_detail': '채용공고 상세',
      'job_about': '업무 소개',
      'requirements_title': '요구사항',
      'organization_about': '회사 소개',
      'address': '주소',
      'specialist_contact': '담당자 연락',
      'employees_count_more_than': '명 이상의 직원',
      'specialist': '담당자',
      'apply': '지원하기',
      'application_closed': '지원 마감',
      'enter_first_last_name': '이름과 성을 입력하세요',
      'application_sent': '지원서가 전송되었습니다',
      'application_failed': '지원서를 전송할 수 없습니다',
      'check_info_before_apply': '지원 전에 정보를 확인하세요',
      'phone_number_label': '전화번호',
      'emergency_assistance': '긴급 지원',
      'select_emergency_situation': '긴급 상황을 선택하세요',
      'medical_care': '의료 지원',
      'Other': '기타',
      'compatriots_around': '주변 동포',
      'no_users_found_nearby': '근처에서 사용자를 찾을 수 없습니다',
      'view_on_map': '지도에서 보기',
      'consular_messages': '영사 메시지'
    },
    'tr': {
      'settings': 'Ayarlar',
      'language': 'Dil',
      'continue': 'Devam et',
      'select_language': 'Dil seçin',
      'select_language_subtitle':
          'Uygulamayı kullanmak için size uygun dili seçin.',
      'appearance': 'Görünüm',
      'theme_mode': 'Tema modu',
      'system_default': 'Sistem varsayılanı',
      'light_mode': 'Aydınlık mod',
      'dark_mode': 'Karanlık mod',
      'change_language': 'Dili değiştir',
      'current_language': 'Geçerli dil',
      'preferences': 'Tercihler',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'Profili düzenle',
      'profile_updated': 'Profil başarıyla güncellendi',
      'save': 'Kaydet',
      'first_name': 'Ad',
      'last_name': 'Soyad',
      'middle_name': 'İkinci ad',
      'username_label': 'Kullanıcı adı',
      'location_unknown': 'Konum bulunamadı',
      'reward_shop': 'Ödül mağazası',
      'logout_confirm_title': 'Çıkış yap',
      'logout_confirm_message': 'Çıkış yapmak istediğinizden emin misiniz?',
      'exit': 'Çıkış',
      'current_location': 'Geçerli konum',
      'tap_to_edit': 'Düzenlemek için dokunun',
      'home_error_title': 'Hata',
      'ok': 'Tamam',
      'news_search_hint': 'Haber ara...',
      'filter_by_date': 'Tarihe göre filtrele',
      'all': 'Tümü',
      'category_news': 'Haberler',
      'events_title': 'Etkinlikler',
      'event_search_hint': 'Etkinlik veya konum ara...',
      'chat_create_group': 'Yeni grup oluştur',
      'chat_group_name': 'Grup adı',
      'chat_group_about_optional': 'Grup hakkında (isteğe bağlı)',
      'city_optional': 'Şehir (isteğe bağlı)',
      'invite_link': 'Davet bağlantısı',
      'example_group_name': 'örnek: group_name',
      'group_type': 'Grup türü',
      'public': 'Herkese açık',
      'private': 'Özel',
      'create': 'Oluştur',
      'chat_create_channel': 'Yeni kanal oluştur',
      'chat_channel_name': 'Kanal adı',
      'chat_channel_about_optional': 'Kanal hakkında (isteğe bağlı)',
      'example_channel_name': 'örnek: channel_name',
      'channel_type': 'Kanal türü',
      'no_groups_yet': 'Henüz grup yok',
      'no_channels_yet': 'Henüz kanal yok',
      'no_chats_yet': 'Henüz sohbet yok',
      'members': 'üye',
      'subscribers': 'abone',
      'nearby_prefix': 'Yakında',
      'edit': 'Düzenle',
      'pin': 'Sabitle',
      'unpin': 'Sabitlemeyi kaldır',
      'delete': 'Sil',
      'edit_message': 'Mesajı düzenle',
      'delete_message_title': 'Silinsin mi?',
      'delete_message_confirm': 'Bu mesajı silmek istediğinize emin misiniz?',
      'no': 'Hayır',
      'yes': 'Evet',
      'edit_group': 'Grubu düzenle',
      'delete_group': 'Grubu sil',
      'leave_group': 'Gruptan çık',
      'edit_channel': 'Kanalı düzenle',
      'delete_channel': 'Kanalı sil',
      'leave_channel': 'Kanaldan çık',
      'chat_group_about': 'Grup hakkında',
      'city': 'Şehir',
      'delete_group_title': 'Grup silinsin mi?',
      'delete_group_confirm': 'Bu grubu kalıcı olarak silmek istediğinize emin misiniz?',
      'yes_delete': 'Evet, sil',
      'delete_channel_title': 'Kanal silinsin mi?',
      'delete_channel_confirm': 'Bu kanalı kalıcı olarak silmek istediğinize emin misiniz?',
      'group': 'Grup',
      'channel': 'Kanal',
      'pinned_message': 'Sabitlenen mesaj',
      'pinned': 'Sabitlendi',
      'edited': 'düzenlendi',
      'career_center_title': 'Kariyer merkezi',
      'no_saved_vacancies': 'Kaydedilen ilan bulunamadı',
      'no_vacancies': 'İlan bulunamadı',
      'retry': 'Tekrar dene',
      'per_month': '/ay',
      'vacancy_not_found': 'İlan bulunamadı',
      'vacancy_detail': 'İlan detayları',
      'job_about': 'İş hakkında',
      'requirements_title': 'Gereksinimler',
      'organization_about': 'Kurum hakkında',
      'address': 'Adres',
      'specialist_contact': 'Uzmanla iletişim',
      'employees_count_more_than': 'çalışandan fazla',
      'specialist': 'Uzman',
      'apply': 'Başvur',
      'application_closed': 'Başvuru kapalı',
      'enter_first_last_name': 'Ad ve soyadı girin',
      'application_sent': 'Başvuru başarıyla gönderildi',
      'application_failed': 'Başvuru gönderilemedi',
      'check_info_before_apply': 'Başvurmadan önce bilgileri kontrol edin',
      'phone_number_label': 'Telefon numarası',
      'emergency_assistance': 'Acil yardım',
      'select_emergency_situation': 'Acil durum seçin',
      'medical_care': 'Tıbbi yardım',
      'Other': 'Diğer',
      'compatriots_around': 'Yakındaki vatandaşlar',
      'no_users_found_nearby': 'Yakında kullanıcı bulunamadı',
      'view_on_map': 'Haritada gör',

      'consular_messages': 'Konsolosluk mesajları'
    },
    'ar': {
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'continue': 'متابعة',
      'select_language': 'اختر اللغة',
      'select_language_subtitle':
          'اختر اللغة الأنسب لك لاستخدام التطبيق.',
      'appearance': 'المظهر',
      'theme_mode': 'وضع السمة',
      'system_default': 'افتراضي النظام',
      'light_mode': 'الوضع الفاتح',
      'dark_mode': 'الوضع الداكن',
      'change_language': 'تغيير اللغة',
      'current_language': 'اللغة الحالية',
      'preferences': 'التفضيلات',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'تعديل الملف الشخصي',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
      'save': 'حفظ',
      'first_name': 'الاسم',
      'last_name': 'اسم العائلة',
      'middle_name': 'الاسم الأوسط',
      'username_label': 'اسم المستخدم',
      'location_unknown': 'الموقع غير متاح',
      'reward_shop': 'متجر المكافآت',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_message': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'exit': 'خروج',
      'current_location': 'الموقع الحالي',
      'tap_to_edit': 'اضغط للتعديل',
      'home_error_title': 'خطأ',
      'ok': 'حسناً',
      'news_search_hint': 'ابحث في الأخبار...',
      'filter_by_date': 'تصفية حسب التاريخ',
      'all': 'الكل',
      'category_news': 'الأخبار',
      'events_title': 'الفعاليات',
      'event_search_hint': 'ابحث عن فعالية أو موقع...',
      'chat_create_group': 'إنشاء مجموعة جديدة',
      'chat_group_name': 'اسم المجموعة',
      'chat_group_about_optional': 'حول المجموعة (اختياري)',
      'city_optional': 'المدينة (اختياري)',
      'invite_link': 'رابط الدعوة',
      'example_group_name': 'مثال: group_name',
      'group_type': 'نوع المجموعة',
      'public': 'عامة',
      'private': 'خاصة',
      'create': 'إنشاء',
      'chat_create_channel': 'إنشاء قناة جديدة',
      'chat_channel_name': 'اسم القناة',
      'chat_channel_about_optional': 'حول القناة (اختياري)',
      'example_channel_name': 'مثال: channel_name',
      'channel_type': 'نوع القناة',
      'no_groups_yet': 'لا توجد مجموعات بعد',
      'no_channels_yet': 'لا توجد قنوات بعد',
      'no_chats_yet': 'لا توجد محادثات بعد',
      'members': 'أعضاء',
      'subscribers': 'مشتركين',
      'nearby_prefix': 'بالقرب',
      'edit': 'تعديل',
      'pin': 'تثبيت',
      'unpin': 'إزالة التثبيت',
      'delete': 'حذف',
      'edit_message': 'تعديل الرسالة',
      'delete_message_title': 'حذف؟',
      'delete_message_confirm': 'هل تريد حذف هذه الرسالة فعلاً؟',
      'no': 'لا',
      'yes': 'نعم',
      'edit_group': 'تعديل المجموعة',
      'delete_group': 'حذف المجموعة',
      'leave_group': 'مغادرة المجموعة',
      'edit_channel': 'تعديل القناة',
      'delete_channel': 'حذف القناة',
      'leave_channel': 'مغادرة القناة',
      'chat_group_about': 'حول المجموعة',
      'city': 'المدينة',
      'delete_group_title': 'حذف المجموعة؟',
      'delete_group_confirm': 'هل تريد حذف هذه المجموعة نهائياً؟',
      'yes_delete': 'نعم، احذف',
      'delete_channel_title': 'حذف القناة؟',
      'delete_channel_confirm': 'هل تريد حذف هذه القناة نهائياً؟',
      'group': 'مجموعة',
      'channel': 'قناة',
      'pinned_message': 'رسالة مثبتة',
      'pinned': 'مثبت',
      'edited': 'تم التعديل',
      'career_center_title': 'مركز الوظائف',
      'no_saved_vacancies': 'لم يتم العثور على وظائف محفوظة',
      'no_vacancies': 'لم يتم العثور على وظائف',
      'retry': 'إعادة المحاولة',
      'per_month': '/شهر',
      'vacancy_not_found': 'الوظيفة غير موجودة',
      'vacancy_detail': 'تفاصيل الوظيفة',
      'job_about': 'حول الوظيفة',
      'requirements_title': 'المتطلبات',
      'organization_about': 'حول المؤسسة',
      'address': 'العنوان',
      'specialist_contact': 'التواصل مع المختص',
      'employees_count_more_than': 'موظف',
      'specialist': 'مختص',
      'apply': 'إرسال الطلب',
      'application_closed': 'تم إغلاق التقديم',
      'enter_first_last_name': 'أدخل الاسم واللقب',
      'application_sent': 'تم إرسال الطلب بنجاح',
      'application_failed': 'تعذر إرسال الطلب',
      'check_info_before_apply': 'تحقق من المعلومات قبل التقديم',
      'phone_number_label': 'رقم الهاتف',
      'emergency_assistance': 'مساعدة الطوارئ',
      'select_emergency_situation': 'اختر حالة طوارئ',
      'medical_care': 'الرعاية الطبية',
      'Other': 'أخرى',
      'compatriots_around': 'المواطنون بالقرب منك',
      'no_users_found_nearby': 'لم يتم العثور على مستخدمين قريبين',
      'view_on_map': 'العرض على الخريطة',
      'consular_messages': 'الرسائل القنصلية'
    },
    'de': {
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'continue': 'Weiter',
      'select_language': 'Sprache auswählen',
      'select_language_subtitle':
          'Wählen Sie die Sprache, die für die App am besten passt.',
      'appearance': 'Darstellung',
      'theme_mode': 'Designmodus',
      'system_default': 'Systemstandard',
      'light_mode': 'Heller Modus',
      'dark_mode': 'Dunkler Modus',
      'change_language': 'Sprache ändern',
      'current_language': 'Aktuelle Sprache',
      'preferences': 'Einstellungen',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': 'Profil bearbeiten',
      'profile_updated': 'Profil erfolgreich aktualisiert',
      'save': 'Speichern',
      'first_name': 'Vorname',
      'last_name': 'Nachname',
      'middle_name': 'Zweiter Vorname',
      'username_label': 'Benutzername',
      'location_unknown': 'Standort nicht verfügbar',
      'reward_shop': 'Belohnungsshop',
      'logout_confirm_title': 'Abmelden',
      'logout_confirm_message': 'Möchten Sie sich wirklich abmelden?',
      'exit': 'Beenden',
      'current_location': 'Aktueller Standort',
      'tap_to_edit': 'Zum Bearbeiten tippen',
      'home_error_title': 'Fehler',
      'ok': 'OK',
      'news_search_hint': 'Nachrichten suchen...',
      'filter_by_date': 'Nach Datum filtern',
      'all': 'Alle',
      'category_news': 'Nachrichten',
      'events_title': 'Veranstaltungen',
      'event_search_hint': 'Veranstaltung oder Ort suchen...',
      'chat_create_group': 'Neue Gruppe erstellen',
      'chat_group_name': 'Gruppenname',
      'chat_group_about_optional': 'Über die Gruppe (optional)',
      'city_optional': 'Stadt (optional)',
      'invite_link': 'Einladungslink',
      'example_group_name': 'zum Beispiel: group_name',
      'group_type': 'Gruppentyp',
      'public': 'Öffentlich',
      'private': 'Privat',
      'create': 'Erstellen',
      'chat_create_channel': 'Neuen Kanal erstellen',
      'chat_channel_name': 'Kanalname',
      'chat_channel_about_optional': 'Über den Kanal (optional)',
      'example_channel_name': 'zum Beispiel: channel_name',
      'channel_type': 'Kanaltyp',
      'no_groups_yet': 'Noch keine Gruppen vorhanden',
      'no_channels_yet': 'Noch keine Kanäle vorhanden',
      'no_chats_yet': 'Noch keine Chats vorhanden',
      'members': 'Mitglieder',
      'subscribers': 'Abonnenten',
      'nearby_prefix': 'In der Nähe',
      'edit': 'Bearbeiten',
      'pin': 'Anheften',
      'unpin': 'Lösen',
      'delete': 'Löschen',
      'edit_message': 'Nachricht bearbeiten',
      'delete_message_title': 'Löschen?',
      'delete_message_confirm': 'Möchten Sie diese Nachricht wirklich löschen?',
      'no': 'Nein',
      'yes': 'Ja',
      'edit_group': 'Gruppe bearbeiten',
      'delete_group': 'Gruppe löschen',
      'leave_group': 'Gruppe verlassen',
      'edit_channel': 'Kanal bearbeiten',
      'delete_channel': 'Kanal löschen',
      'leave_channel': 'Kanal verlassen',
      'chat_group_about': 'Über die Gruppe',
      'city': 'Stadt',
      'delete_group_title': 'Gruppe löschen?',
      'delete_group_confirm': 'Möchten Sie diese Gruppe wirklich dauerhaft löschen?',
      'yes_delete': 'Ja, löschen',
      'delete_channel_title': 'Kanal löschen?',
      'delete_channel_confirm': 'Möchten Sie diesen Kanal wirklich dauerhaft löschen?',
      'group': 'Gruppe',
      'channel': 'Kanal',
      'pinned_message': 'Angeheftete Nachricht',
      'pinned': 'Angeheftet',
      'edited': 'bearbeitet',
      'career_center_title': 'Karrierezentrum',
      'no_saved_vacancies': 'Keine gespeicherten Stellen gefunden',
      'no_vacancies': 'Keine Stellen gefunden',
      'retry': 'Erneut versuchen',
      'per_month': '/Monat',
      'vacancy_not_found': 'Stelle nicht gefunden',
      'vacancy_detail': 'Stellendetails',
      'job_about': 'Über die Stelle',
      'requirements_title': 'Anforderungen',
      'organization_about': 'Über die Organisation',
      'address': 'Adresse',
      'specialist_contact': 'Spezialisten kontaktieren',
      'employees_count_more_than': 'Mitarbeitende',
      'specialist': 'Spezialist',
      'apply': 'Bewerben',
      'application_closed': 'Bewerbung geschlossen',
      'enter_first_last_name': 'Vorname und Nachname eingeben',
      'application_sent': 'Bewerbung erfolgreich gesendet',
      'application_failed': 'Bewerbung konnte nicht gesendet werden',
      'check_info_before_apply': 'Prüfen Sie die Angaben vor der Bewerbung',
      'phone_number_label': 'Telefonnummer',
      'emergency_assistance': 'Notfallhilfe',
      'select_emergency_situation': 'Wählen Sie einen Notfall aus',
      'medical_care': 'Medizinische Versorgung',
      'Other': 'Sonstiges',
      'compatriots_around': 'Landsleute in der Nähe',
      'no_users_found_nearby': 'Keine Benutzer in der Nähe gefunden',
      'view_on_map': 'Auf der Karte anzeigen',
      'consular_messages': 'Konsularische Mitteilungen'
    },
    'zh': {
      'settings': '设置',
      'language': '语言',
      'continue': '继续',
      'select_language': '选择语言',
      'select_language_subtitle': '请选择最适合您的应用语言。',
      'appearance': '外观',
      'theme_mode': '主题模式',
      'system_default': '跟随系统',
      'light_mode': '浅色模式',
      'dark_mode': '深色模式',
      'change_language': '更改语言',
      'current_language': '当前语言',
      'preferences': '偏好设置',
      'language_uz': 'O\'zbekcha',
      'language_en': 'English',
      'language_ru': 'Русский',
      'language_ko': '한국어',
      'language_tr': 'Türkçe',
      'language_ar': 'العربية',
      'language_de': 'Deutsch',
      'language_zh': '中文',
      'edit_profile': '编辑个人资料',
      'profile_updated': '个人资料已成功更新',
      'save': '保存',
      'first_name': '名字',
      'last_name': '姓氏',
      'middle_name': '中间名',
      'username_label': '用户名',
      'location_unknown': '无法获取位置',
      'reward_shop': '奖励商店',
      'logout_confirm_title': '退出登录',
      'logout_confirm_message': '确定要退出登录吗？',
      'exit': '退出',
      'current_location': '当前位置',
      'tap_to_edit': '点击编辑',
      'home_error_title': '错误',
      'ok': '确定',
      'news_search_hint': '搜索新闻...',
      'filter_by_date': '按日期筛选',
      'all': '全部',
      'category_news': '新闻',
      'events_title': '活动',
      'event_search_hint': '搜索活动或地点...',
      'chat_create_group': '创建新群组',
      'chat_group_name': '群组名称',
      'chat_group_about_optional': '群组介绍（可选）',
      'city_optional': '城市（可选）',
      'invite_link': '邀请链接',
      'example_group_name': '例如：group_name',
      'group_type': '群组类型',
      'public': '公开',
      'private': '私密',
      'create': '创建',
      'chat_create_channel': '创建新频道',
      'chat_channel_name': '频道名称',
      'chat_channel_about_optional': '频道介绍（可选）',
      'example_channel_name': '例如：channel_name',
      'channel_type': '频道类型',
      'no_groups_yet': '暂无群组',
      'no_channels_yet': '暂无频道',
      'no_chats_yet': '暂无聊天',
      'members': '成员',
      'subscribers': '订阅者',
      'nearby_prefix': '附近',
      'edit': '编辑',
      'pin': '置顶',
      'unpin': '取消置顶',
      'delete': '删除',
      'edit_message': '编辑消息',
      'delete_message_title': '删除？',
      'delete_message_confirm': '确定要删除这条消息吗？',
      'no': '否',
      'yes': '是',
      'edit_group': '编辑群组',
      'delete_group': '删除群组',
      'leave_group': '退出群组',
      'edit_channel': '编辑频道',
      'delete_channel': '删除频道',
      'leave_channel': '退出频道',
      'chat_group_about': '群组介绍',
      'city': '城市',
      'delete_group_title': '删除群组？',
      'delete_group_confirm': '确定要永久删除这个群组吗？',
      'yes_delete': '是，删除',
      'delete_channel_title': '删除频道？',
      'delete_channel_confirm': '确定要永久删除这个频道吗？',
      'group': '群组',
      'channel': '频道',
      'pinned_message': '置顶消息',
      'pinned': '已置顶',
      'edited': '已编辑',
      'career_center_title': '职业中心',
      'no_saved_vacancies': '未找到已保存职位',
      'no_vacancies': '未找到职位',
      'retry': '重试',
      'per_month': '/月',
      'vacancy_not_found': '未找到职位',
      'vacancy_detail': '职位详情',
      'job_about': '职位介绍',
      'requirements_title': '要求',
      'organization_about': '机构介绍',
      'address': '地址',
      'specialist_contact': '联系专员',
      'employees_count_more_than': '名员工',
      'specialist': '专员',
      'apply': '申请',
      'application_closed': '申请已关闭',
      'enter_first_last_name': '请输入名字和姓氏',
      'application_sent': '申请已成功提交',
      'application_failed': '无法提交申请',
      'check_info_before_apply': '申请前请检查信息',
      'phone_number_label': '电话号码',
      'emergency_assistance': '紧急援助',
      'select_emergency_situation': '请选择紧急情况',
      'medical_care': '医疗护理',
      'Other': '其他',
      'compatriots_around': '附近的同胞',
      'no_users_found_nearby': '附近未找到用户',
      'view_on_map': '在地图上查看',
      'consular_messages': '领事消息'
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String translateWithParams(String key, Map<String, String> params) {
    var value = translate(key);
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }

  static String translateStatic(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static String translateStaticWithParams(
    String key,
    String languageCode,
    Map<String, String> params,
  ) {
    var value = translateStatic(key, languageCode);
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'uz', 'ru']
          .contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
